### ISSUE TITLE
Add `plugins` field with plugin configs as first level citizens

### ISSUE THREAD

**Issue by tuliren** [stoat-dev/stoat-action#54]
The current `tasks` field has task configs as its first level citizen. This can be weird for global plugins (i.e. plugins that only needs to be configured once per repo). For example, the `job_runtime` should only be included in one task, but currently it is possible to set it in multiple tasks.

A stoat config schema that can enforce the uniqueness of global plugins is as follows. It adds a `plugins` field, under which plugin configs are first level citizens:

```yaml
----
version: 1
enabled: true
plugins:
  static_hosting:
    jest-coverage-report:
      path: /coverage/lcov-report
      metadata:
        name: `jest` report
    jacoco-report
      path: /build/jacoco/report
      metadata:
        name: `jacoco` report
  job_runtime:
```

However, it is possible that it is not a good idea. A plugin that is "global" today may not be the case tomorrow. For example, there may be legit use cases for setting up `job_runtime` tasks multiple times so that different jobs can have their runtime chart presented in different styles or formats. So we should not rush in the implementation of this issue.
